config/routes.rb
Niceweather::Application.routes.draw do
  resources :images

  resources :favorites

  resources :comments

  resources :users

  resources :recipes

  resources :ingredient_sets

  resources :ingredients

  resources :ingredient_groups

  get "home/index"
  resources :type_sets

  resources :types

  get '/register', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :sessions, only: [:new, :create, :destroy]

   root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :recipeid, :userid, :isban, :comment
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :recipeid, :userid
  belongs_to :user
  belongs_to :recipe
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :recipeid, :userid
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :groupid
  belongs_to :ingredient_group
  has_many :ingredient_sets
  has_many :recipes, :through => :ingredient_sets
end

app/models/ingredient_group.rb
class IngredientGroup < ActiveRecord::Base
  	attr_accessible :name
  has_many:ingredients
end

app/models/ingredient_set.rb
class IngredientSet < ActiveRecord::Base
  attr_accessible :recipeid, :ingredientid, :amountnum, :unitofmeasure
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :userid, :title, :description, :isban, :imageid, :favnum
  has_many :ingredient_sets
  has_many :ingredients, :through => :ingredient_sets
  has_many :comments
  has_many :favorites
  belongs_to :user
  has_one :image
end

app/models/type.rb
class Type < ActiveRecord::Base
	attr_accessible :name
	has_many :type_sets
end

app/models/type_set.rb
class TypeSet < ActiveRecord::Base
	attr_accessible :typeid, :recipeid
	belongs_to :type
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name , :email, :password, :password_confirmation, :remember_token
	has_secure_password

  has_many :recipes
  has_many :favorites
  has_many :comments
  has_one :image

	before_save do
  		self.email.downcase! if self.email
  	end
  	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation, presence: true
	
	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

 	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
 	end

	private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.where("userid=?",current_user.id)
  end

  def show
    #get comments from db
    @comments = Comment.where("recipeid = ? AND isban = ?", set_recipe.id , false)

    #create new comment
    @comment = Comment.new
    @all_users=User.all
    @all_recipes=Recipe.all

    #create new favorite
    @favorite = Favorite.new

  end

#Create new recipe
  def new
    @recipe = Recipe.new
    @all_users=User.all
    @all_ingredients=Ingredient.all
    @all_types=Type.all
  end


  def edit
    @recipe = set_recipe
    @all_users=User.all
    @all_ingredients=Ingredient.all
  end

#Save the new recipe into db
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.userid=current_user.id
    @recipe.isban=false
    @recipe.favnum=0

    respond_to do |format|
      if @recipe.save
        
        #save the ingredients into db
        params[:ingredients][:id].each do |ingre|
          if !ingre.empty?
           @ingredientset=IngredientSet.new(:ingredientid => ingre, :recipeid => @recipe.id)            
           @ingredientset.save
          end
        end

        #save the types into db
        params[:types][:id].each do |type|
          if !type.empty?
            @typeset=TypeSet.new(:typeid => type,:recipeid => @recipe.id)
            @typeset.save
          end
        end

        #save the image into db
        dir ="#{Rails.root}/app/assets/images/Recipe/#{@recipe.id}"

        Dir.mkdir(dir) unless File.exists?(dir)

        uploaded_io = params[:recipe][:image]
        File.open(Rails.root.join('app', 'assets','images', 'Recipe', @recipe.id.to_s, uploaded_io.original_filename), 'wb') do |file|
          file.write(uploaded_io.read)
        end
        @image=Image.new(:recipeid => @recipe.id, :name => uploaded_io.original_filename)
        @image.save

        
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'new', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:userID, :title, :description, :isBan, :imageID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user==current_user
  end

  def sign_out 
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to]= request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end


end 

app/helpers/type_sets_helper.rb
module TypeSetsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	#Returns the Gravatar for the given user. 
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

 <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label "All Ingredients" %><br />
    <%= collection_select(:ingredients,:id,@all_ingredients,:id,:name,{},{:multiple => true})%>
  </div>

  <div class="field">
    <%= f.label "All Types" %><br />
    <%= collection_select(:types,:id,@all_types,:id,:name,{},{:multiple => true})%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/created.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @recipe.userid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Isban:</strong>
  <%= @recipe.isban %>
</p>

<p>
  <strong>Imageid:</strong>
  <%= @recipe.imageid %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div id="center">
  <ul id="recipe">
    <h2>My Recipes</h2>
    <% @recipes.each do |recipe| %>
    <li>
      <%=link_to image_tag("Recipe/"+recipe.id.to_s+"/"+Image.find_by(recipeid:
		 recipe.id).name, :alt => "recipe"),recipe %>
      <span>
	<%= link_to recipe.title, recipe, :id => "title" %>
      </span>
      <br /><br />
      <span>
	<%= link_to User.find(recipe.userid).name,
	    User.find(recipe.userid), :id => "author" %>
      </span>
      <br /><br />
      <span>
	Main Ingredients:
	<% IngredientSet.where("recipeid = ?", recipe.id).each do |set| %>
	<text class="ing"><%= Ingredient.find(set.ingredientid).name %></text>
	<% end %>
      </span>
      <br /><br />
      <span id="favorite">
	Favorited By : <%= Favorite.where("recipeid =
					   ?",recipe.id).count %> Users
      </span>
      <span>
	&nbsp;&nbsp;&nbsp;
	Posted On : <%= recipe.created_at %>
      </span>
    </li>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag("Recipe/"+@recipe.id.to_s+"/"+Image.find_by(recipeid: @recipe.id).name, :alt => "recipe") %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= User.find(@recipe.userid).name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Ingredients:</strong>
  <% IngredientSet.where("recipeid = ?",@recipe.id).each do |set| %>
  <%= Ingredient.find(set.ingredientid).name %>
  <% end %>
</p>

<p>
  <strong>Types:</strong>
  <% TypeSet.where("recipeid = ?",@recipe.id).each do |set| %>
  <%= Type.find(set.typeid).name %>
  <% end %>
</p>

<!--<p>
    <strong>Isban:</strong>
    <%= @recipe.isban %>
</p>-->

<!--<p>
    <strong>Imageid:</strong>
    <%= @recipe.imageid %>
</p>-->

<% if signed_in? %>
<div id="favorite">

  <%= form_for(@favorite) do |f| %>  
  <%= f.hidden_field :recipeid,:value => @recipe.id %>
  <div class="actions">
    <!--user hasn't added it to favorite-->
    <% if Favorite.find_by(userid: current_user.id,recipeid:
    @recipe.id).nil? %>
    <%= f.submit 'Like' %>
    <% else %>
    <!--user has already added it into favorite-->
    <%= f.submit 'Dislike' %>
    <% end %>
  </div>
  <% end %>

</div>
<% end %>


<!-- for showing existed comments -->
<div id="comment">
  <h2>Comments:</h2>
  <% @comments.each do |comment| %>
  <p>
    <strong><%= User.find(comment.userid).name %>:</strong>
    <%= comment.comment %>
  </p>
  <% end %>
</div>

<!-- for adding a new comment -->
<% if signed_in? %>
<div id="add_comment">

  <%= form_for(@comment) do |f| %>

  <%= f.hidden_field :recipeid,:value => @recipe.id %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit 'Add Comment' %>
  </div>
  <% end %>
</div>
<% end %>