config/routes.rb
Niceweather::Application.routes.draw do
  resources :images

  resources :favorites

  resources :comments

  resources :users

  resources :recipes

  resources :ingredient_sets

  resources :ingredients

  resources :ingredient_groups

  get "home/index"
  resources :type_sets

  resources :types

  get '/register', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :sessions, only: [:new, :create, :destroy]

   root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :recipeid, :userid, :isban, :comment
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :recipeid, :userid
  belongs_to :user
  belongs_to :recipe
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :recipeid, :userid
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :groupid
  belongs_to :ingredient_group
  has_many :ingredient_sets
  has_many :recipes, :through => :ingredient_sets
end

app/models/ingredient_group.rb
class IngredientGroup < ActiveRecord::Base
  	attr_accessible :name
  has_many:ingredients
end

app/models/ingredient_set.rb
class IngredientSet < ActiveRecord::Base
  attr_accessible :recipeid, :ingredientid, :amountnum, :unitofmeasure
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :userid, :title, :description, :isban, :imageid, :favnum
  has_many :ingredient_sets
  has_many :ingredients, :through => :ingredient_sets
  has_many :comments
  has_many :favorites
  belongs_to :user
  has_one :image
end

app/models/type.rb
class Type < ActiveRecord::Base
	attr_accessible :name
	has_many :type_sets
end

app/models/type_set.rb
class TypeSet < ActiveRecord::Base
	attr_accessible :typeid, :recipeid
	belongs_to :type
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name , :email, :password, :password_confirmation, :remember_token
	has_secure_password

  has_many :recipes
  has_many :favorites
  has_many :comments
  has_one :image

	before_save do
  		self.email.downcase! if self.email
  	end
  	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation, presence: true
	
	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

 	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
 	end

	private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/type_sets_controller.rb
class TypeSetsController < ApplicationController
  before_action :set_type_set, only: [:show, :edit, :update, :destroy]

  # GET /type_sets
  # GET /type_sets.json
  def index
    @type_sets = TypeSet.all
  end

  # GET /type_sets/1
  # GET /type_sets/1.json
  def show
  end

  # GET /type_sets/new
  def new
    @type_set = TypeSet.new
  end

  # GET /type_sets/1/edit
  def edit
  end

  # POST /type_sets
  # POST /type_sets.json
  def create
    @type_set = TypeSet.new(type_set_params)

    respond_to do |format|
      if @type_set.save
        format.html { redirect_to @type_set, notice: 'Type set was successfully created.' }
        format.json { render action: 'show', status: :created, location: @type_set }
      else
        format.html { render action: 'new' }
        format.json { render json: @type_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_sets/1
  # PATCH/PUT /type_sets/1.json
  def update
    respond_to do |format|
      if @type_set.update(type_set_params)
        format.html { redirect_to @type_set, notice: 'Type set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @type_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_sets/1
  # DELETE /type_sets/1.json
  def destroy
    @type_set.destroy
    respond_to do |format|
      format.html { redirect_to type_sets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_set
      @type_set = TypeSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_set_params
      params.require(:type_set).permit(:recipeID, :typeID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user==current_user
  end

  def sign_out 
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to]= request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end


end 

app/helpers/type_sets_helper.rb
module TypeSetsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	#Returns the Gravatar for the given user. 
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/type_sets/_form.html.erb
<%= form_for(@type_set) do |f| %>
  <% if @type_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_set.errors.count, "error") %> prohibited this type_set from being saved:</h2>

      <ul>
      <% @type_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipeid %><br>
    <%= f.number_field :recipeid %>
  </div>
  <div class="field">
    <%= f.label :typeid %><br>
    <%= f.number_field :typeid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/type_sets/edit.html.erb
<h1>Editing type_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @type_set %> |
<%= link_to 'Back', type_sets_path %>

app/views/type_sets/index.html.erb
<h1>Listing type_sets</h1>

<table>
  <thead>
    <tr>
      <th>Recipeid</th>
      <th>Typeid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @type_sets.each do |type_set| %>
      <tr>
        <td><%= type_set.recipeid %></td>
        <td><%= type_set.typeid %></td>
        <td><%= link_to 'Show', type_set %></td>
        <td><%= link_to 'Edit', edit_type_set_path(type_set) %></td>
        <td><%= link_to 'Destroy', type_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type set', new_type_set_path %>

app/views/type_sets/new.html.erb
<h1>New type_set</h1>

<%= render 'form' %>

<%= link_to 'Back', type_sets_path %>

app/views/type_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipeid:</strong>
  <%= @type_set.recipeid %>
</p>

<p>
  <strong>Typeid:</strong>
  <%= @type_set.typeid %>
</p>

<%= link_to 'Edit', edit_type_set_path(@type_set) %> |
<%= link_to 'Back', type_sets_path %>